### ISSUE TITLE
when open www, the update dont  work,

### ISSUE THREAD

**Issue by L0ngxhn** [bosefirmware/ced#1]
When the firmware page is opened, the update program can not run properly and the page will report an error. 

"That did't work. Refresh your browser or relaunch the Bose Updater, then try again."

but when i used old firmware ,it ok . so what ?

**Comment by L0ngxhn** [comment]
i think   firmware can't connect page,but firewall is closed.

**Comment by bosefirmware** [comment]
Just checked on Windows 10 & macOS. Both work, please redownload, follow steps and try again.
