### ISSUE TITLE
Issue trying to downgrade SoundLink Mini II

### ISSUE THREAD

**Issue by KarlFochtmann** [bosefirmware/ced#10]
I have followed the instructions and the the downgrade version appear in the drop down menu with your Updater Program. I am on version 1.1.4 and try to downgrade to 1.1.3 but it reports error **There are no available updates for this product.**

I dont know if this issue is known or not, and any clue how to get around this?

Many Thanks

**Comment by bosefirmware** [comment]
I checked, it still works. Please re-read over the instructions as all errors found so far have been people missing a step. 

If you are still having the same issue try on a different computer or even better ask someone else to follow the instructions and do it for you without you helping them.
