### ISSUE TITLE
[VERSION ERROR]Updater warning the version is lower

### ISSUE THREAD

**Issue by Lysanleo** [bosefirmware/ced#15]
Platform: Windows10
The latest version of BOSEUPDATER is 7.0.4.4795, and the edited exe is 4388. 
I think that's why the update process didn't allowed.

If there has any solution for this problem?

**Comment by rainvalley** [comment]
The same to your situation.

**Comment by Lysanleo** [comment]
In addition, the headphone is qc 35 ii

**Comment by bosefirmware** [comment]
Updated files
