### ISSUE TITLE
Bose 700 support? 

### ISSUE THREAD

**Issue by ChristopheRoyer21** [bosefirmware/ced#16]
Hello,
I don't see the Bose 700 on the list at the end, but it wasn't clear what is the list for. I just ask it in case: Is it possible to use this program to downgrade the Bose NC 700?
Thank you

**Comment by Voxoff** [comment]
Currently investigating the same thing - this reddit post suggests it is ok: https://www.reddit.com/r/bose/comments/gs94bh/bose_700_nc_redwhite_led_flashing_solutionnotice/

**Comment by bosefirmware** [comment]
The Bose Noise Cancelling Headphones 700's have been able to be downgraded using this method for a while now.
