### ISSUE TITLE
NC700 new firmware

### ISSUE THREAD

**Issue by scorpio2k2** [bosefirmware/ced#3]
Hello,

Do you have a new fw for nc700?

**Comment by bosefirmware** [comment]
1.1.4 is the current latest version
https://community.bose.com/t5/Around-On-Ear-Headphones/Noise-Cancelling-Headphones-700-Firmware-Update-1-1-4-June-30/m-p/216079

**Comment by miemieking** [comment]
> 1.1.4 是当前最新版本 https://community.bose.com/t5/Around-On-Ear-Headphones/Noise-Cancelling-Headphones-700-Firmware-Update-1-1-4-June-30/m-p/216079
Do you have the firmware of BOS E700 version 2.0.4?
