### ISSUE TITLE
Downgrading firmware with Bose Update v7.1.7.5136

### ISSUE THREAD

**Issue by kukdh1** [bosefirmware/ced#38]
I found that the `BOSEUPDATER.EXE` has special option to change URL of LOOKUP file.
Tested on Windows 10, with NC700.
Bose Update version is 7.1.7.5136.

1. Open https://btu.bose.com/ and download the Bose Updater.
2. Install the Bose Updater.
3. Close the Bose Updater if automatically executed.
4. Open CMD/Terminal and go to `C:\Program Files (x86)\Bose Updater`
`cd "C:\Program Files (x86)\Bose Updater"`
6. Run `BOSEUPDATER.EXE` with `-d` option: 
`BOSEUPDATER.EXE -d https://raw.githubusercontent.com/bosefirmware/ced/master/lookup.xml`
7. Open https://btu.bose.com/ again. (Note: they may require you to login with Bose account)
8. Enter advanced mode ('a', 'd', 'v', 'Arrow up', 'Arrow down').
9. Now you can select the version to proceed.
![image](https://github.com/bosefirmware/ced/assets/6904750/3cf9db3d-efc4-4637-8db4-9b49e8a66349)
(Note: I already downgraded to v1.3.1)
10. Click "Update Now" to downgrade.

**Comment by zhangjiesg** [comment]
good

**Comment by mlazzje** [comment]
Thank you @kukdh1 !!!

**Comment by jefro108** [comment]
Using a Mac the instructions are similar
Tested on macOS Ventura 13.4.1, with NC700.
Bose Update version is 7.1.7.5136.

1. Open https://btu.bose.com/ and download the Bose Updater.
2. Install the Bose Updater.
3. Close the Bose Updater if automatically executed.
4. Open Terminal and run Bose Updater with -d option: `'/Applications/Bose Updater.app/Contents/MacOS/Bose Updater' -d https://raw.githubusercontent.com/bosefirmware/ced/master/lookup.xml`
5. Open https://btu.bose.com/ again. (You can use the 'Launch Bose Updater Webpage' option from the Menu Bar)
6. Enter advanced mode ('a', 'd', 'v', 'Arrow up', 'Arrow down').
7. Now you can select the version to proceed. 
![image](https://github.com/bosefirmware/ced/assets/12976435/c48e14df-709d-44fc-93be-63564e714989)
8. Click "Update Now" to downgrade.

**Comment by Bhaalgorn** [comment]
not working on the latest version 7.1.13.5138
shows "unknown option 'd' "

**Comment by kukdh1** [comment]
Wow, it looks like BOSE is tracking this repository :astonished:
The option name has been changed to different one, and I think it is better to not disclose it.

You can find it by yourself:
1. Decompress executable (BOSEUPDATER.exe) using [upx](https://upx.github.io/).
2. Open with hex editor (e.g., HxD) and search for `url`.
3. You will find few words after `url`, delimited by non-alphanumeric characters. Try them as an option name (with two hyphens).
4. If you got error saying "missing value for the option", that should be the answer.
(Of course, you can disassemble the code instead of brute-forcing.)

**Comment by Canawan** [comment]
Hello sir, I have a bose quietcomfort earbud and want to downgrade the firmware, can you make a more detailed guide, because I'm not very good with technology
