### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by mttw000** [bosefirmware/ced#7]
![Untitled](https://user-images.githubusercontent.com/64454059/80445683-75303b80-8947-11ea-8883-d9409a0607d9.png)

I'm getting this error

**Comment by TiovenR** [comment]
The latest version is 4454. The new version cannot find the word "connected_device" in HxD. I can't change it, the old version will prompt me to update the program before I can use it.

**Comment by lgrullon-gilead** [comment]
I am in the same boat, I think bose is messing things up for those of us trying to downgrade.

**Comment by bosefirmware** [comment]
I checked, it still works. Please make sure you've downloaded the most recent windows or mac version from the github.

**Comment by bosefirmware** [comment]
Yes Bose changed things around, but there is a version you can download in the github that will work.
